### ISSUE TITLE
200 ok for users that don't exist

### ISSUE THREAD

**Issue by rootVIII** [meanii/Search4#13]
Hey there 7rillionaire... were there sites that give a 200 ok even if the user does not exist? I can create a fix for that.

I am just not sure which websites give the 200 when the user doesn't exist though.

Are there particular sites/urls that you know of that have this problem?

**Comment by OxNu11** [comment]
👀 nice! 

I should give you all the links by today [here](https://github.com/7rillionaire/Search4/blob/master/sites.md#need) I will let you know after adding them

**Comment by ghost** [comment]
If I am not wrong, you mean
`sites which give 200 response  for non-existing users & throw  error messages?`
Or I didn't understood you and so @OxNu11, sorry 
I was adding  new status_code based sites to [.yml](https://github.com/7rillionaire/Search4/commit/5e9750863bd7b8bfe5be6126dc1041581593defe) so maybe I mis read that

By the way, here are the sites  (for which I think you were asking)
```
"Archive.org": https://archive.org/details/@{{ username }}

Dribble: https://dribbble.com/{{ username }}

Ebay: https://www.ebay.com/usr/{{ username }}

GitLab: https://gitlab.com/{{ username }}

HackerOne: https://hackerone.com/{{ username }}

HackerRank: https://hackerrank.com/{{ username }}

Instructables: https://www.instructables.com/member/{{ username }}

Kik: https://ws2.kik.com/user/{{ username }}

Roblox: https://www.roblox.com/user.aspx?username={{ username }}
 
ProductHunt: https://www.producthunt.com/@{{ username }}
 
Steam: https://steamcommunity.com/id/{{ username }}

Telegram: https://t.me/{{ username }}

TikTok: https://www.tiktok.com/@{{ username }}

Tinder: https://www.gotinder.com/@{{ username }}

Trello: https://trello.com/{{ username }}

Bandcamp: https://www.bandcamp.com/{{ username }}

Flipboard: https://flipboard.com/@{{ username }}

Docker: https://hub.docker.com/u/{{ username }}/
```

**Comment by rootVIII** [comment]
Yup I think those are the ones. I’ll close the issue for now and see what i can come up with sometime over the next week. Thanks!
