### ISSUE TITLE
Twitter error on user name. 

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [meanii/Search4#14]
Hello, 

I check my accounts, and found that script makes error on Twitter.  There is url with response not found.
Given username is SEOTrafficHack

**[[!] Twitter : Account not found on https://twitter.com/SEOTrafficHack](url)**
social sites:
[!] VK : Account not found on https://m.vk.com/SEOTrafficHack
[!] Google+ : Account not found on https://plus.google.com/+SEOTrafficHack
[!] Twitter : Account not found on https://twitter.com/SEOTrafficHack
[!] Dev.to : Account not found on https://dev.to/SEOTrafficHack
[!] MyAnimeList : Account not found on https://myanimelist.net/profile/SEOTrafficHack

> facebook: Account found on https://www.facebook.com/SEOTrafficHack

**Comment by rootVIII** [comment]
This should be fixed in #15 as long as it gets merged...

**Comment by ghost** [comment]
Yep! #15 is merged & has fixed those issues
